<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVD1TdLr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVD1TdLr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVD1TdLr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVD1TdLr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVD1TdLr\App_KernelDevDebugContainer([
    'container.build_hash' => 'VD1TdLr',
    'container.build_id' => '0913b545',
    'container.build_time' => 1667228615,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVD1TdLr');
